### ISSUE TITLE
[BUG] Unable to play sound on headset

### ISSUE THREAD

**Issue by Remi4001** [tofodroid/mimi-mod#130]
**Describe the bug**
When trying to set the audio output using the device config, my headset isn't listed in "Available System Devices".

**To Reproduce**
1. Right-click with "Device config" item
2. Scroll through "Available System Devices"
3. Notice "Headset" isn't there

**Expected behavior**
I should be able to output sound directly to my headset.

**Screenshots**
- Here I tried manually setting the output to my headset, but it didn't work. Also there is no more than 6 available system devices, 1 and 2 being integrated audio and 3 to 6 being hdmi/displayport audio) :
![image](https://github.com/tofodroid/mimi-mod/assets/49501893/d55e43f3-c17b-4fe1-a411-9c7629088cb2)

- But in Minecraft's options I can see my Headset :
![image](https://github.com/tofodroid/mimi-mod/assets/49501893/3ac4a50c-f836-4460-af88-bc2f60b871c2)

**Environment (please complete the following information):**
 - OS: [Arch Linux 6.9.1]
 - Mod Versions: [3.1.5 and 4.0.8] (screenshots are from 3.1.5)
 - Minecraft Version: [1.20.1]
 - Forge Version: [1.20.1 - 47.2.0]

**Additional context**
Output of `alsactl info`, notice "Headset" (card 2) is listed here:
```
#
# Sound card
#
- card: 0
  id: PCH
  name: HDA Intel PCH
  longname: HDA Intel PCH at 0x4402110000 irq 174
  driver_name: HDA-Intel
  mixer_name: Realtek ALC897
  components: HDA:10ec0897,10438814,00100402
  controls_count: 48
  pcm:
    - stream: PLAYBACK
      devices:
        - device: 0
          id: ALC897 Analog
          name: ALC897 Analog
          subdevices:
            - subdevice: 0
              name: subdevice #0
        - device: 1
          id: ALC897 Digital
          name: ALC897 Digital
          subdevices:
            - subdevice: 0
              name: subdevice #0
    - stream: CAPTURE
      devices:
        - device: 0
          id: ALC897 Analog
          name: ALC897 Analog
          subdevices:
            - subdevice: 0
              name: subdevice #0
        - device: 2
          id: ALC897 Alt Analog
          name: ALC897 Alt Analog
          subdevices:
            - subdevice: 0
              name: subdevice #0
  hwdep:
    - device: 0
      id: HDA Codec 0
      name: HDA Codec 0
      iface: 16
#
# Sound card
#
- card: 1
  id: NVidia
  name: HDA NVidia
  longname: HDA NVidia at 0xa1080000 irq 17
  driver_name: HDA-Intel
  mixer_name: Nvidia GPU a5 HDMI/DP
  components: HDA:10de00a5,10de17ff,00100100
  controls_count: 28
  pcm:
    - stream: PLAYBACK
      devices:
        - device: 3
          id: HDMI 0
          name: VG27B
          subdevices:
            - subdevice: 0
              name: subdevice #0
        - device: 7
          id: HDMI 1
          name: HDMI 1
          subdevices:
            - subdevice: 0
              name: subdevice #0
        - device: 8
          id: HDMI 2
          name: HDMI 2
          subdevices:
            - subdevice: 0
              name: subdevice #0
        - device: 9
          id: HDMI 3
          name: HDMI 3
          subdevices:
            - subdevice: 0
              name: subdevice #0
  hwdep:
    - device: 0
      id: HDA Codec 0
      name: HDA Codec 0
      iface: 16
#
# Sound card
#
- card: 2
  id: Headset
  name: PRO X Wireless Gaming Headset
  longname: Logitech PRO X Wireless Gaming Headset at usb-0000:00:14.0-6, full speed
  driver_name: USB-Audio
  mixer_name: USB Mixer
  components: USB046d:0aba
  controls_count: 6
  pcm:
    - stream: PLAYBACK
      devices:
        - device: 0
          id: USB Audio
          name: USB Audio
          subdevices:
            - subdevice: 0
              name: subdevice #0
    - stream: CAPTURE
      devices:
        - device: 0
          id: USB Audio
          name: USB Audio
          subdevices:
            - subdevice: 0
              name: subdevice #0
```
